CREATE TABLE IF NOT EXISTS teacher_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    lesson_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_availability_teacher FOREIGN KEY (teacher_id) REFERENCES teacher(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_teacher_avail_teacher ON teacher_availability(teacher_id);
